"""add_order_to_chain_call_logs

Revision ID: 96c81ed8b56c
Revises: 1131167fbdbf
Create Date: 2026-02-26 20:37:57.951297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c81ed8b56c'
down_revision: Union[str, Sequence[str], None] = '1131167fbdbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chain_call_logs', sa.Column('order', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chain_call_logs', 'order')
    # ### end Alembic commands ###
