"""add model_pricing table

Revision ID: a7ef5ba20297
Revises: b5fa12101aa7
Create Date: 2026-03-19 15:59:57.641351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ef5ba20297'
down_revision: Union[str, Sequence[str], None] = 'b5fa12101aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('input_cost_per_token', sa.Numeric(), nullable=True),
    sa.Column('output_cost_per_token', sa.Numeric(), nullable=True),
    sa.Column('max_input_tokens', sa.Integer(), nullable=True),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('supports_vision', sa.Boolean(), nullable=False),
    sa.Column('supports_function_calling', sa.Boolean(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_pricing_model_name'), 'model_pricing', ['model_name'], unique=True)
    op.create_index(op.f('ix_model_pricing_provider'), 'model_pricing', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_pricing_provider'), table_name='model_pricing')
    op.drop_index(op.f('ix_model_pricing_model_name'), table_name='model_pricing')
    op.drop_table('model_pricing')
    # ### end Alembic commands ###
