"""add model_name to chain_call_logs

Revision ID: b5fa12101aa7
Revises: c3d4e5f6a7b8
Create Date: 2026-03-19 15:18:39.250959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5fa12101aa7'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_runs_stats'), table_name='agent_runs')
    op.add_column('chain_call_logs', sa.Column('model_name', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_chain_call_logs_agent_id_called_at'), table_name='chain_call_logs')
    op.drop_index(op.f('ix_chain_call_logs_agent_run_order'), table_name='chain_call_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chain_call_logs_agent_run_order'), 'chain_call_logs', ['agent_id', 'run_id', 'call_order'], unique=False)
    op.create_index(op.f('ix_chain_call_logs_agent_id_called_at'), 'chain_call_logs', ['agent_id', 'called_at'], unique=False)
    op.drop_column('chain_call_logs', 'model_name')
    op.create_index(op.f('ix_agent_runs_stats'), 'agent_runs', ['agent_id', 'started_at', 'status', 'ended_at'], unique=False)
    # ### end Alembic commands ###
