"""add token usage columns to chain_call_logs

Revision ID: c31dc371d24b
Revises: a7ef5ba20297
Create Date: 2026-03-19 17:59:03.581872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c31dc371d24b'
down_revision: Union[str, Sequence[str], None] = 'a7ef5ba20297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chain_call_logs', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('chain_call_logs', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('chain_call_logs', sa.Column('total_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chain_call_logs', 'total_tokens')
    op.drop_column('chain_call_logs', 'completion_tokens')
    op.drop_column('chain_call_logs', 'prompt_tokens')
    # ### end Alembic commands ###
